CREATE TABLE recruitment_db.dbo.UPLOADED_APPLICATION_INFO (
	ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	FILE_ID BIGINT NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	FULL_NAME VARCHAR(255) NOT NULL,
	MOBILE_NO VARCHAR(255) NOT NULL,
	STATUS VARCHAR(255) NOT NULL,
	INSERTED_AT DATETIME2 NULL,
	UPDATED_AT DATETIME2 NULL
);

CREATE TABLE recruitment_db.dbo.UPLOADED_FILE_INFO (
	ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	FILE_NAME VARCHAR(255) NOT NULL,
	TOTAL_APPLICATION BIGINT NOT NULL,
	INSERTED_AT DATETIME2 NULL,
	UPDATED_AT DATETIME2 NULL
);

CREATE TABLE recruitment_db.dbo.USERS (
	ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	EMAIL varchar(255) NULL,
	USERNAME varchar(255) NULL,
	FIRST_NAME varchar(255) NULL,
	LAST_NAME varchar(255) NULL,
	PASSWORD varchar(255) NULL,
	PHONE_NUMBER varchar(255) NULL,
	STATUS varchar(255) NULL,
);


INSERT INTO recruitment_db.dbo.USERS
(EMAIL, USERNAME, FIRST_NAME, LAST_NAME, PASSWORD, PHONE_NUMBER, STATUS)
VALUES('ovi821@gmail.com', 'avijit_bairagi', 'Avjit', 'Bairagi', '$2a$10$EOLTUzcSTANo9anNHVhiRelnX9XlryU2gNDXrC2v2G5mws6PtsTqe', '+8801735657837', 'Active');

INSERT INTO recruitment_db.dbo.USERS
(EMAIL, USERNAME, FIRST_NAME, LAST_NAME, PASSWORD, PHONE_NUMBER, STATUS)
VALUES('admin@admin.com', 'admin', 'Admin', 'Admin', '$2a$10$EOLTUzcSTANo9anNHVhiRelnX9XlryU2gNDXrC2v2G5mws6PtsTqe', '', 'Active');

